# Generated by Django 4.0.6 on 2022-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
