# Generated by Django 4.0.6 on 2022-07-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_others_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='others',
        ),
    ]
